fail_fast: true
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        require_serial: true
  - repo: local
    hooks:
      - id: pytype
        name: pytype
        entry: poetry run pytype
        language: system
        types: [python]
        require_serial: true
